// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkrfhlycvtmpoewlwpcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrcmZobHljdnRtcG9ld2x3cGNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMDQ5MzAsImV4cCI6MjA2MDY4MDkzMH0.0-BOBZt63tT7zTv-wiVrcYNaX1UWR1br0ZDgm-uSvgU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);